-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th12 25, 2021 lúc 03:52 PM
-- Phiên bản máy phục vụ: 10.4.22-MariaDB
-- Phiên bản PHP: 8.0.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `bookstore`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `cart`
--

CREATE TABLE `cart` (
  `Customer` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `Product` varchar(40) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `Quantity` int(5) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `cart`
--

INSERT INTO `cart` (`Customer`, `Product`, `Quantity`) VALUES
('suyashgulati', 'ENT-12', 1),
('suyash', 'NEW-4', 5),
('suyashgulati', 'ENT-1', 3),
('suyash', 'BIO-3', 5),
('suyashgulati', 'CHILD-1', 6),
('suyashgulati', 'NEW-1', 1),
('nimisha', 'NEW-2', 1),
('nimisha', 'ENT-7', 1),
('suyash', 'ENT-12', 1),
('suyashgulati', 'ENT-1222', 1),
('suyash', 'ENT-1', 1);

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `products`
--

CREATE TABLE `products` (
  `PID` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `Title` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `Author` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `MRP` float NOT NULL,
  `Price` float NOT NULL,
  `Discount` int(11) DEFAULT NULL,
  `Available` int(11) NOT NULL,
  `Publisher` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Edition` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Category` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `Description` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `Language` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `page` int(5) DEFAULT NULL,
  `weight` int(4) DEFAULT 500
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `products`
--

INSERT INTO `products` (`PID`, `Title`, `Author`, `MRP`, `Price`, `Discount`, `Available`, `Publisher`, `Edition`, `Category`, `Description`, `Language`, `page`, `weight`) VALUES
('ENT1', 'Tuyển sinh vào 10: Môn toán', 'Nguyễn Sơn Hà\r\nPhạm Minh Phương\r\nNguyễn Thị Hợp', 75, 50, 10, 200, 'Đại học sư phạm', '2', 'Thi tuyển sinh', 'Nội dung gồm có: Phần một. Hướng dẫn ôn tập, Chủ đề 1: Căn bậc hai. Căn bậc ba, Chủ đề 2: Hàm số bậc nhất, Chủ đề 3: Hệ phương trình bậc nhất hai ẩn, ...', 'Tiếng việt', 115, 50),
('ENT2', 'Tuyển sinh vào 10: Môn Văn', 'Nguyễn Đức Hùng', 90, 75, 15, 122, 'Đại học quốc gia hà nội', '1', 'Entrance Exam', 'Trong sách này tác giả cung cấp dàn ý nhằm giúp các em xác định, định hướng nội dung, và sau đó là các bài văn tiêu biểu đã được triển khai một cách hàm súc nhất, để các em có cơ sở tham khảo và vận dụng theo cách của mình. Để rồi từ kiến thức vững vàng đó, các em sẽ đủ cơ sở để thi vào các trường công lập và các trường chuyên THPT.', 'Tiếng việt', 155, 45),
('ENT3', 'Tuyển sinh vào 10: Môn Tiếng ', 'Bùi Ánh Dương\r\nBùi Thanh Hương\r\nTrần Thị Yến', 115, 90, 18, 90, 'Đại học sư phạm', '1', 'Entrance Exam', 'Cuốn sách Ôn tập thi tuyển sinh vào môn tiếng anh năm học 2020 - 2021 do Bùi Ánh Dương làm chủ biên dựa trên nền tảng là chủ đề, kiến thức ngữ pháp - từ vựng và kỹ năng theo chương trình sách giáo khoa...', 'English, Tiếng việt', 250, 50),
('ENT4', 'Thi tuyển sinh vào 10: Môn Sinh ', 'Lê Thị Hà', 75, 50, 10, 82, 'Đại học quốc gia hà nội', '', 'Entrance Exam', 'Nội dung gồm có:, Phần một. Đề thi tuyển sinh vào lớp 10 chuyên, - Đề số 1, - Đề số 2 , - Đề số 3, ........., - Đề số 30, Đáp án, Phần hai. Đề thi học ...', 'Tiếng việt', 156, 55),
('ENT5', 'Thi tuyển sinh vào 10: Môn Lịch Sử', 'Lê Thị Hà', 65, 50, 8, 2, 'Đại học quốc gia hà nội', '1', 'Entrance Exam', 'Tổng hợp đề thi học sinh giỏi 9 và đề vào 10 chuyên sử có đáp án chi tiết,', 'Tiếng việt', 95, 30),
('ENT06', 'Cẩm nang tuyển sinh đại học & cao đẳng 2021', 'Nhóm phóng viên giáo dục báo tuổi trẻ', 250, 200, 15, 215, 'Nhóm phóng viên giáo dục báo tuổi trẻ', '15', 'Entrance Exam', 'Xét tuyển từ kết quả thi đánh giá năng lực đã trở thành một phương thức tuyển sinh ngày càng được nhiều trường ĐH, CĐ chọn lựa những năm gần đây. Số lượng trường ĐH đứng ra tổ chức kỳ thi này ngày càng nhiều, chỉ tiêu các trường dùng để xét kết quả cũng không ngừng mở rộng. Đến đầu năm nay, chỉ riêng kỳ thi đánh giá năng lực của ĐH Quốc gia TP.HCM tổ chức năm 2021 dự kiến đã có gần 50 trường tham gia xét tuyển. Một số trường ĐH khác cũng tiếp tục thực hiện kỳ thi riêng để xét tuyển vào trường như: Việt Đức, Quốc tế, Nguyễn Tất Thành, Công nghệ TP.HCM…', 'Tiếng Việt', 200, 50),
('ENT7', 'Cẩm nang tuyến sinh đại học & cao đẳng 2020', 'Nhóm phóng viên giáo dục báo tuổi trẻ', 260, 199, 30, 60, 'Báo tuổi trẻ', '1', 'Entrance Exam', '', 'Tiếng việt', 200, 50),
('ENT8', 'Thi tuyển sinh vào 10: Môn địa lý', 'Nguyễn Minh Tuệ', 25, 19, 8, 125, 'Đại học sư phạm', '4', 'Entrance Exam', 'Kì thi tuyển sinh đánh giá năng lực vào lớp 10 THPT sắp diễn ra. Để giúp các thầy cô và các em học sinh có tài liệu tham khảo trong quá trình giảng ...', 'Tiếng việt', 90, 25),
('LIT1', 'Hoàn tử bé', 'Antoine de Saint-Exupéry', 250, 225, 15, 87, 'Kim đồng', '1', 'Literature and Fiction', 'Hoàng tử bé sống trên tiểu tinh cầu B612. Ở đó có ba ngọn núi lửa (hai ngọn đang hoạt động còn ngọn kia thì không) và một bông hoa hồng. Cậu chăm sóc cho tiểu hành tinh của mình hằng ngày, nhổ hết các cây bao báp định bám rễ, mọc lên tại đây. Những cái rễ đó sẽ xói đục hành tinh và làm cho thế giới cậu đang sống bị xé rách ra. Một ngày nọ, hoàng tử bé đã rời hành tinh của mình và đi xem phần còn lại của vũ trụ xem như thế nào và đã tới một vài tiểu tinh cầu khác (có số từ 325 đến 330), mỗi tinh cầu này có một người lớn sống ở đó và theo cách hiểu của cậu thì họ toàn là những người kỳ quặc.', 'Tiếng việt', 225, 50),
('LIT2', 'Ông già và biển cả', 'Ernest Hemingway', 145, 130, 8, 67, '', '1', 'Literature and Fiction', 'Là một tiểu thuyết ngắn được Ernest Hemingway viết ở Cuba năm 1951 và xuất bản năm 1952. Nó là truyện ngắn dạng viễn tưởng cuối cùng được viết bởi Hemingway. Đây cũng là tác phẩm nổi tiếng và là một trong những đỉnh cao trong sự nghiệp sáng tác của nhà văn. Tác phẩm này đoạt giải Pulitzer cho tác phẩm hư cấu năm 1953. Nó cũng góp phần quan trọng để nhà văn được nhận Giải Nobel văn học năm 1954.', 'Tiếng việt', 275, 50),
('LIT3', 'Dế mèn phiêu lưu ký', 'Tô Hoài', 80, 49, 45, 48, 'Kim Đồng', '1', 'Literature and Fiction', 'Đây là tác phẩm đặc biệt ấn tượng của Tô Hoài dành cho trẻ em và trở thành một phần ký ức tuổi thơ của không ít thế hệ trẻ Việt Nam. Câu chuyện phiêu lưu của chú dế mèn được nhà văn kể lại qua lăng kính hết sức gần gũi với con trẻ cùng ngôn ngữ nhẹ nhàng, không nặng về tính chất giáo dục nên dễ đọc, dễ hiểu và dễ cảm nhận. ', 'Tiếng Việt', 125, 25),
('LIT4', 'Văn học dân gian', 'Lê Xuân Mậu', 50, 25, 50, 78, 'Lao động', '1', 'Literature and Fiction', 'Cũng nhờ tìm được ngữ cảnh giả định khá đặc biệt, tác giả cùng ta hiểu ra cái ý cái nghĩa rất mới mẻ độc đáo của những câu hát về con vỏi con voi hay về con gà cục tác lá chanh… Rất nhiều “bức tranh cuộc sống” được vẽ lên trong ca dao có được sắc màu lung linh đủ cho những người có khả năng cảm thụ văn chương tinh tế cũng có thể yêu thích được.', 'Tiếng Việt', 45, 12),
('LIT5', 'Không gia đình', 'Hector Malot ', 195, 135, 31, 23, 'Kim Đồng', '1', 'Literature and Fiction', 'Tác phẩm xoay quanh em bé không người thân thích, có tên là Remi. Để kiếm sống, em bé phải đi theo một đoàn xích và em đã làm quen với cụ Vitali, những người bạn động vật là khỉ, chó…', 'Tiếng Việt', 250, 80),
('LIT6', 'Những ngày thơ ấu', 'Nguyên Hồng', 175, 123, 30, 27, 'NXB Văn Học', '1', 'Literature and Fiction', 'Trong văn đàn văn học Việt Nam, nhà văn Nguyên Hồng được đồng nghiệp và độc giả ưu ái gọi bằng danh hiệu “Nhà văn của phụ nữ và trẻ em”. Nguyên Hồng từng có một tuổi thơ bất hạnh. Hồi kí “Những ngày thơ ấu” được coi là những dòng hồi ức chân thực, sinh động và đầy cay đắng về tuổi thơ không êm đềm của tác giả.Trong tác phẩm của Nguyên Hồng, hình ảnh người phụ nữ và trẻ em trong xã hội cũ được nhà văn dành cho niềm yêu thương đồng cảm.', 'Tiếng Việt', 200, 80),
('LIT7', 'Tuổi thơ dữ dội ', 'Phùng Quán', 250, 160, 36, 34, 'NXB Văn Học', '1', 'Literature and Fiction', 'Tuổi thơ dữ dội là cuốn tiểu thuyết của nhà văn Phùng Quán. Truyện được viết vào năm 1968 và hoàn thành vào năm 1986. Vào năm 1988, tiểu thuyết được xuất bản và đến năm 1990 được nhận Giải thưởng Văn học Thiếu nhi của Hội Nhà văn Việt Nam. Đến nay, tác phẩm đã được dựng thành phim.\r\n\r\nCuốn truyện xoay quanh Đội thiếu niên trinh sát của trung đoàn Trần Cao Vân – những thiếu niên 13, 14 tuổi đầy nhiệt huyết và lòng yêu nước. Mặc dù hoàn cảnh mỗi người mỗi khác nhưng họ có chung lòng yêu nước, căm thù giặc.', 'Tiếng Việt', 184, 75),
('LIT8', 'Tôi thấy hoa vàng trên cỏ xanh', 'Nguyễn Nhật Ánh', 150, 100, 30, 56, 'NXB ', '1', 'Literature and Fiction', 'Cuốn sách văn học Việt Nam hay xuất sắc gợi nhớ cho tôi một thế giới đầy những bất ngờ và hương vị thơ ngây cùng những suy nghĩ giản dị đến bình dị nhưng lại toát lên vẻ đẹp và gần gũi đến lạ thường. Câu chuyện \"Tôi thấy hoa vàng trên cỏ xanh\" có những lúc bấp bênh khúc này, khúc kia nên mỗi ai khi đọc cuốn sách này đều thấy mình trong đó nó mang đậm hương vị của một là thứ tình đầu đời của cu Thiều chẳng hạn... ngây thơ và khờ khạo.', 'Tiếng Việt', 302, 115),
('CHILD1', 'Ngoan ngoãn', 'Nhiều tác giả', 35, 20, 36, 56, 'NXB Trẻ', '1', 'Children and Teens', 'Bộ sách Gieo mầm tính cách cho bé yêu – sách thiếu nhi nên đọc được biên soạn dành cho độ tuổi nhỏ hơn, với hình ảnh 4 màu sinh động hơn, với những tính cách được lựa chọn gần gũi với độ tuổi nhỏ của các bé yêu hơn. Tính cách của trẻ được hình thành từ rất sớm, thông qua sự giáo dục trong gia đình, qua những việc làm, lời nói, cách ứng xử của những người xung quanh. ', 'Tiếng Việt', 50, 15),
('CHILD2', '101 Câu chuyện', 'Công Minh - Hà Huy', 45, 29, 36, 89, 'NXB Đà Nẵng', '1', 'Children and Teens', 'Bộ sách 101 câu chuyện hàn gắn dành cho trẻ em và thanh thiếu niên gồm 2 tập, kể những câu chuyện hấp dẫn, sáng tạo được các bác sĩ giàu kinh nghiệm áp dụng trong việc điều trị nhằm giúp đỡ trẻ em và thanh thiếu niên lĩnh hội những bài học quan trọng nhất trong cuộc sống, tạo cơ hội để chúng được giúp đỡ, thậm chí biết cách suy nghĩ theo hướng phòng bệnh hơn chữa bệnh, góp phần phát triển những kỹ năng lành mạnh và tạo ra một cuộc sống tốt đẹp hơn cho chính bản thân mình.', 'Tiếng Việt', 65, 18),
('CHILD3', 'Nếp gấp thời gian', 'Madeleine L\'Engle', 85, 49, 30, 101, 'NXB Văn Học', '1', 'Children and Teens', 'Đó là một đêm giông bão mịt mùng. Meg Murry cùng em trai nhỏ Charles Wallace và mẹ đang ở trong bếp thì một vị khách rầy rà nhất trần đời xuất hiện.\r\n\r\n\"Những đêm bão là ta khoái lắm đấy,\" người lạ kỳ cục bảo ba mẹ con. \"Chỉ có điều ta bị luồng gió cuốn phăng đi, rồi bị thổi trệch cả đường... Ta sẽ ngồi xuống một lát, đi ủng vào và sau đó lên đường. Nói đến chuyện đường xá, nhân đây, có tồn tại cái vật gọi là khối lập phương bốn chiều, cưng ạ.\"\r\n\r\nBố của Meg trong khi đang thử nghiệm du hành xuyên thời gian ở chiều thứ năm, đột nhiên biến mất vô cùng bí ẩn. Giờ đây đã đến lúc cho Meg, Calvin bạn cô, cùng Charles Wallace lên đường giải cứu ông, đối mặt với Quyền lực Bóng tối. Cuộc hành trình xuyên qua không gian bao la đã được trí tưởng tượng kỳ diệu của nhà văn ban cho những chiều kích mới.', 'Tiếng Việt', 95, 25),
('CHILD4', 'Hạt giống tâm hồn', 'Nhiều tác giả', 55, 39, 30, 55, 'NXB Tổng hợp TP.HCM', '1', 'Children and Teens', 'Cuốn “Hạt giống tâm hồn” có một câu nói của Oprah Winfey rằng: “Cuộc sống luôn chứa đựng những nổi đau mà ta không thể nào đoán trước được. Thế nhưng hãy tin rằng mọi chuyện buồn điều lướt qua chúng ta rất nhanh như một đoạn phim ngắn”. Cuốn sách đem lại nhiều cảm xúc cho người đọc, mỗi người sẽ có những cảm nhận riêng về cuốn sách. Riêng tôi, sự kiên cường ý chí vươn lên chống lại chông gai của từng nhân vật trong cuốn sách là cảm nhận tôi từ họ.', 'Tiếng Việt', 220, 50),
('REG1', 'Bí quyết chinh phục kỹ năng đọc hiểu tiếng anh', 'Hoàng Bảo - Dương Hương', 100, 65, 35, 12, 'NXB ĐHQG Hà Nội', '6', 'Regional Books', '', 'Tiếng Anh, Tiếng Việt', 77, 100),
('REG2', 'Ngữ pháp tiếng Pháp căn bản', 'Nguyễn Thức Thành Tín', 550, 399, 35, 60, 'NXB ĐH SP TP.HCM', '1', 'Regional Books', 'Tổng hợp ngữ pháp căn bản của tiếng Pháp', 'Tiếng Pháp, Tiếng Việt', 224, 120),
('REG3', 'Tự học tiếng Nhật cấp tốc', 'Hải Quỳnh', 295, 207, 30, 9, 'NXB Thời đại', '1', 'Regional Books', '', 'Tiếng Nhật, Tiếng Việt', 376, 500),
('REG4', 'Tự học tiếng Trung', 'Thu Trang', 195, 137, 30, 6, 'NXB Hồng Đức', '1', 'Regional Books', '', 'Tiếng Trung, Tiếng Việt', 235, 500),
('BUS1', 'Think and Grow Rich', 'Napoleon Hill', 250, 199, 20, 88, 'Ross Cornwell', '1', 'Business and Management', 'Think and grow rich – 13 nguyên tắc nghĩ giàu, làm giàu là cuốn sách “chỉ dẫn” duy nhất chỉ ra những nguồn lực bạn phải có để thành công. Mỗi chương trong cuốn sách đều đề cập đến bí quyết kiếm tiền, từ việc có niềm tin, có mong muốn đến những kiến thức chuyên sâu, những ý tưởng, những kế hoạch, những cách đưa ra quyết định.', 'Tiếng Việt', 200, 60),
('BUS2', 'Cha giàu cha nghèo', 'Robert Kiyosaki', 200, 149, 39, 199, 'NXB Văn Hóa - Thông tin', '3', 'Business and Management', 'Cha giàu cha nghèo nói về nguyên do khiến tác giả Robert Kiyosaki được như ngày hôm nay chính là đúc kết từ những quan điểm và ý kiến trái chiều từ hai người cha thân thiết của mình. \r\n\r\nChính vì xuất thân và hoàn cảnh có phần khác biệt này đã khiến cho tác giả cảm thấy phân vân và khó xử vì người cha nào cũng đều đưa ra những lời khuyên trái ngược dành cho ông.\r\n\r\nĐối với người cha ruột thì cho rằng: “Ham mê tiền bạc là nguồn gốc của mọi điều xấu”, còn người cha nuôi kia thì lại phản bác rằng: “Thiếu thốn tiền bạc là nguồn gốc của mọi điều xấu”.', 'Tiếng Việt', 250, 90),
('BUS3', 'Cà phê cùng Tony ', 'Tony', 250, 199, 39, 225, 'NXB Trẻ', '3', 'Business and Management', 'Cuốn sách Tony buổi sáng - Cà phê cùng Tony là tập hợp những bài viết trên mạng xã hội của tác giả Tony về những lời khuyên, kinh nghiệm, định hướng, chia sẻ mà anh tự rút ra trong cuộc sống qua những bức bối, thói quen xấu, tư tưởng nhỏ nhoi mà người Việt Nam hay mắc phải. Anh chia sẻ từ những chuyện nhỏ nhặt, tưởng chừng như đơn giản như ăn mặc, vệ sinh, giao tiếp, ứng xử, chuyện ngủ… sao cho văn minh, lịch sự đến những chuyện lớn lao trong cuộc đời mỗi người như học tập, kinh doanh, giải quyết thất nghiệp, đạo đức làm người…', 'Tiếng Việt', 215, 60),
('BUS4', 'Người bán hàng vĩ đại nhất thế giới', 'Og Mandino', 300, 149, 51, 95, 'NXB Tổng hợp TP.HCM', '6', 'Business and Management', '“Người bán hàng vĩ đại nhất thế giới” (The Greatest Salesman in the World) là một cuốn sách về Marketing, được viết bởi Og Mandino, phục vụ như một hướng dẫn cho một triết lý về bán hàng, và thành công, kể câu chuyện về Hafid, một cậu bé lạc đà nghèo khổ, đạt được một cuộc sống phong phú.\r\n\r\nTôi gần như đã đọc rất nhiều sách về bán hàng, nhưng tôi cho là Og Mandino đã tổng hợp hầu hết nội dung của các sách ấy lại vào cuốn “Người bán hàng vĩ đại nhất thế giới”. Không ai sẽ thất bại trong vai trò người bán hàng, nếu theo sát các nguyên tắc trong cuốn sách này, và cũng không ai có thể trở thành vĩ đại trong nghề mà không có chúng.', 'Tiếng Việt', 265, 115),
('BUS5', 'Đừng bao giờ bỏ cuộc', 'Donald J.Trump', 165, 149, 15, 85, 'NXB Trẻ', '2', 'Business and Management', 'Trump – Đừng bao giờ bỏ cuộc doanh nhân nổi tiếng nhất thế giới này thẳng thắn giãi bày những thách thức to lớn nhất, những giây phút tệ hại nhất, và những cuộc chiến khốc liệt nhất – và cách ông biến những nghịch cảnh đó thành các thành công mới.\r\n\r\nCuốn sách còn đưa ra những lời khuyên đắt giá trong kinh tế về: cách phản pháo khi gặp thất bại và trở ngại; biến những vấn đề lớn thành những cơ hội thậm chí còn lớn hơn; cách biến kẻ thù và địch thủ thành bạn bè và đồng minh; cách tận dụng những thất bại trước mắt làm động lực cho bản thân bạn – và khiến bạn kiên cường hơn.', 'Tiếng Việt', 295, 120),
('BUS6', 'Dạy con làm giàu', 'Robert Kiyosaki', 300, 169, 10, 232, 'NXB Trẻ', '2', 'Business and Management', 'Cuốn sách dạy con: Cách suy nghĩ về đồng tiền sẽ quyết định tương lai và sự giàu có của bạn.\r\n\r\nCó rất nhiều phương pháp để tôi và bạn cải thiện cuộc sống và thu nhập, nhưng với Dạy Con Làm Giàu của tác giả Robert Kiyosaki, bạn sẽ biết được chìa khóa nền tảng để trở nên giàu có hơn.\r\n\r\nNếu như bạn muốn có thật nhiều tiền, tiêu pha vô tư thì bạn hãy đọc Dạy Con Làm Giàu vì cuốn sách kinh tế này giới thiệu vô vàn kiến thức bổ ích về thị trường marketing và tình hình tài chính sau này của bạn.', 'Tiếng Việt', 362, 500),
('BUS7', 'Đừng bao giờ đi ăn một mình', 'Keith Ferrazzi', 495, 470, 5, 12, 'NXB Trẻ', '2', 'Business and Management', 'Bạn mong muốn đi tắt đón đầu? Bạn muốn vững bước đến thành công? Công thức để làm được điều này, theo lời bậc thầy về kết nối là Keith Ferrazzi, chính là phải biết làm quen với mọi người. Ferrazzi đã khám phá từ khi còn trẻ rằng điểm đặc biệt của những người thành công thẫm mỹ chính là cách họ vận dụng quyền năng của những mối quan hệ giao tiếp – để mọi người cùng thắng.\r\n\r\nTrong quyển sách Đừng bao giờ đi ăn một mình (Never Eat Alone), Ferrazzi cũng chỉ ra từng bước cách thức – và lý do – mà chính ông đã áp dụng để kết nối với hàng ngàn người là đồng nghiệp, bạn bè có tên trong số danh bạ, đó là những người ông đã giúp đỡ và ngược lại cũng chuẩn bị giúp đỡ ông.\r\n\r\n', 'Tiếng Việt', 355, 500),
('BUS8', 'Nhà lãnh đạo không chức danh', 'Robin Sharma ', 450, 199, 50, 323, 'NXB Trẻ', '10', 'Business and Management', 'Cho dù bạn làm gì trong tổ chức và cuộc sống hiện nay của bạn như thế nào, một thực tế quan trọng duy nhất là bạn hoàn toàn có khả năng thể hiện năng lực để làm lãnh đạo. Cho dù sự nghiệp hiện nay của bạn đang ở đâu, bạn vẫn luôn cần thể hiện các khả năng tột đỉnh của mình. Cuốn sách này sẽ hướng dẫn bạn làm thế nào để khai thác tối đa khả năng trong chính bạn, cũng như thay đổi cuộc sống và thế giới ở quanh bạn.', 'Tiếng Việt', 185, 60),
('NEW0001', 'Nhật ký covid', '#', 175, 110, 36, 125, 'NXB Trẻ', '1', 'New', 'Để yên cho bác sĩ “hiền” – Nhật ký Covid và những chuyện chưa kể: cuốn bút ký của bác sĩ Ngô Đức Hùng, nhìn Covid-19 từ lăng kính của một bác sĩ ở tâm dịch. Đây là những trang nhật ký muôn màu muôn vẻ từ những ngày tháng trực tiếp tham gia tuyến đầu chống dịch của bác sĩ Ngô Đức Hùng – một bác sĩ của khoa Cấp cứu, Bệnh viện Bạch Mai. Đó vừa là những chia sẻ chuyên môn của bác sĩ về dịch bệnh, vừa là những ghi chép về công sức và tâm tư của những con người ngày đêm đứng ở tuyến đầu phòng dịch, những trang nhật ký về con người, về tình người trong những ngày Covid hoành hành.', 'Tiếng Việt\r\n', 280, 500),
('NEW0002', 'Tương lai sau đại dịch covid', 'Jason Schenker', 129, 68, 43, 6, 'NXB Thế Giới', '9', 'new', 'Tương lai sau đại dịch Covid của Jason Schenker, chuyên gia dự báo hàng đầu trong lĩnh vực thị trường tài chính, người được liệt vào danh sách cố vấn tài chính có tầm ảnh hưởng nhất thế giới. Cuốn sách đưa ra hàng loạt dự báo ở mọi lĩnh vực về một thế giới sau thảm họa đại dịch: giáo dục, y tế, truyền thông, kinh tế, chính trị. Trong bối cảnh đại dịch Covid đang nhanh chóng làm thay đổi toàn bộ đời sống xã hội ở quy mô chưa từng có, cuốn sách hứa hẹn đóng vai trò như “một tấm bản đồ dẫn đường” trong một trật tự thế giới mới được thiết lập sau đại dịch. ', 'Tiếng Việt', 320, 500),
('NEW0003', 'Thuật Quyết Định - Suy nghĩ thông minh, làm việc sáng suốt', 'Steve Mcclatchy', 259, 199, 33, 150, 'NXB Hồng Đức', '1', 'new', 'Đưa ra những quyết định đúng  được chính mình hay được mọi người ủng hộ và thực thi là cả một nghệ thuật sống +  làm việc mà bất kỳ ai đều phải có. Ai chẳng muốn có thêm thời gian, tiền bạc việc QUYẾT ĐỊNH THÔNG MINH cho bạn thêm thời gian, mối quan hệ, tiền…cuốn sách Thuật Quyết Định - Suy nghĩ thông minh, làm việc sáng suốt sẽ chỉ lối bạn từ lý thuyết đến công cụ để có thể đưa ra những quyết định có chiều sâu và đúng việc, mang lại cuộc sống tuyệt vời cho cuộc đời bạn.', 'Tiếng Việt', 280, 500),
('NEW0004', 'Kế hoạch quản lý tài chính cá nhân', 'Vicki Robin & Joe Domiguez', 435, 289, 34, 22, 'NXB Hồng ', '2', 'new', 'Nếu bạn muốn quản lý tài chính – Kiểm soát – Tiết Kiệm – Đầu tư tiền thì hay sở hữu ngay cho mình cuốn sách quản lý tài chính cá nhân của Bizbooks. Đây sẽ là cuốn cẩm nang vàng  cung cấp cho bạn những phương pháp, giá trị cốt lõi quan trọng trong quản lý tài chính giúp bạn có thể tự do về mặt tài chính, khiến bản thân luôn có cuộc sống sung túc hơn và có một khoản tiền để hiện thực hóa giấc mơ, phát triển trên con đường mà mình đã lựa chọn.\r\n\r\n', 'Tiếng Việt', 245, 150),
('HEA1', 'Về nhà ăn cơm', 'Đức Nguyễn', 90, 69, 18, 88, 'NXB Thế giới', '1', 'Health and Cooking', 'Về nhà ăn cơm là cuốn sách dạy nấu ăn đầu tiên trong toplist này mà bạn nhất định phải biết đến. Thấu hiểu được nhu cầu ăn chay tăng dần của giới trẻ hiện nay, tác giả Đức Nguyễn đã cho ra đời cuốn sách bổ ích này. Các món ăn chay ngày nay được chế biến đa dạng, cầu kì và nhiều dinh dưỡng hơn.', 'Tiếng Việt', 332, 500),
('HEA2', 'Dinh dưỡng chìa khóa vàng cho sức khỏe', 'Lisa Hark', 105, 89, 20, 12, 'NXB Phụ nữ', '1', 'Health and Cooking', '', 'Tiếng Việt', 148, 50),
('HEA3', 'Hai căn bếp ngọt ngào', 'Đào Chi Anh & Nguyễn Hoàng Anh', 150, 99, 35, 69, 'NXB Phụ Nữ', '1', 'Health and Cooking', 'Sweet Kitchen là cuốn sách dạy nấu ăn chuyên về các công thức đồ ngọt, và cũng là đứa con tinh thần đã được ấp ủ từ rất lâu trước khi Chi Anh và Hoàng Anh tìm thấy nhau qua niềm đam mê ẩm thực. Được nhà xuất bản Page One Publishing tại Singapore ra mắt phiên bản tiếng Anh toàn cầu, Sweet Kitchen đã nâng tầm tác giả Việt lên ngang hàng cùng các ấn phẩm sách chất lượng quốc tế.\r\n\r\n', 'Tiếng Việt', 122, 45),
('HEA4', 'Ăn xanh để ', 'Norman W.Walker', 115, 99, 15, 130, 'NXB Lao Động', '1', 'Health and Cooking', 'hời gian phải là yếu tố duy nhất quyết định bạn già hay trẻ. Công thức của sự trẻ trung còn có cả yếu tố về sức khỏe thể chất và tinh thần. Chưa bao giờ là quá muộn để bắt đầu trẻ hóa. Những gì bạn ăn, làm và suy nghĩ sẽ quyết định độ tuổi thật của chính bạn', 'Tiếng Việt', 190, 60),
('HEA5', 'Suối nguồn tươi trẻ', 'Peter Kelder', 150, 99, 45, 125, 'NXB Trẻ', '1', 'Health and Cooking', 'Điều quý giá nhất trong cuộc đời mỗi con người không phải là tiền bạc hay công danh, sự nghiệp mà chính là “Sức khỏe”. Có sức khỏe mới có thể yêu thương, mới có điều kiện và động lực để hoàn thành ước mơ, hoài bão mà bạn theo đuổi. Vnwriter mong rằng 8 cuốn sách hay về sức khỏe sau đây sẽ giúp bạn xây dựng lối sống lành mạnh và khoa học, hoàn thành được các mục tiêu trong đời.', 'Tiếng Việt', 128, 40),
('HEA6', 'Những quy tắc để sống khỏe', 'Alphabook', 159, 99, 35, 110, 'NXB Lao Động', '1', 'Health and Cooking', 'Sức khỏe là vàng, là tài sản quý giá nhất của con người – có sức khỏe là có tất cả.\r\n\r\nNhưng đâu phải ai cũng biết chăm sóc sức khỏe cho mình  bởi cuộc sống hiện đại gấp gáp, ai ai cũng dễ bị cuốn vào guồng quay của công việc, dễ bỏ bê việc chăm sóc sức khỏe của chính bản thân mình.\r\n\r\nJoyce Meyer từng nói: “Tôi tin rằng món quà lớn nhất mà bạn có thể trao cho gia đình mình và thế giới này chính là sức khỏe của bạn”\r\n\r\nCó sức khỏe tốt, bạn mới có thể yêu thương, biết trân trọng cuộc sống, có động lực và điều kiện để thực hiện ước mơ, hoài bão.\r\n\r\nVì thế nên bạn và gia đình, người thân hãy quan tâm đến sức khỏe, chăm sóc sức khỏe để luôn duy trì 1 cuộc sống khỏe mạnh, vui vẻ.', 'Tiếng Việt', 55, 2),
('LIT-13', 'She Broke Up I Didnt! I Just Kissed Someone Else!', 'Robert Kyosaki\r\n', 175, 113, 35, 8, 'Penguin Books', '1', 'Literature & Fiction', NULL, 'English', 248, 500),
('LIT-14', 'When Only Love Remains', 'Durjoy Datta', 175, 113, 35, 7, 'Metro Reads', '1', 'Literature & Fiction', NULL, 'English', 288, 500),
('LIT-15', 'Till the Last Breath', 'Durjoy Datta', 175, 113, 35, 8, 'Penguin Books', '1', 'Literature & Fiction', NULL, 'English', 256, 500),
('LIT-16', 'Our Impossible Love', 'Durjoy Datta', 175, 123, 30, 8, 'Metro Reads', '1', 'Literature & Fiction', 'Life teaches us what love truly is And love gives definition to life \r\nAisha, a bit of a late bloomer, has to figure out what it means to be a woman and to be desired. Danish feels time is running out for him and he s going to end up as a nobody, as opposed to his overachieving, determined younger brother.\r\nLife takes a strange turn when Danish, the confused idiot, is appointed as the student counsellor to Aisha. Between the two of them they have to figure out love, life, friendship most of all, themselves. And it s not proving to be . . . easy\'\r\nOur Impossible Love presents Life the way it is and Love the way it should be', 'English', 256, 500),
('LIT-17', 'One Night @ The Call Centre', 'Chetan Bhagat', 176, 114, 35, 8, 'Rupa Publications', '1', 'Literature & Fiction', 'One Night at the Call Centre is a witty, romantic and humorous story of six call center employees by India s bestselling author, Chetan Bhagat. \r\n\r\nOne Night at the Call Center is set in one night in a call center in Gurgaon. The call center employees provide technical assistance to American consumers and help them run their lives smoothly. The six friends Shyam, Priyanka, Esha, Vroom, Radhika, and Military Uncle somehow try to make it through the shift as tonight was no ordinary night. It is Thanksgiving in America and the phone lines are going crazy! Then one call, from a very special caller changes everything. This phone call is from God! One Night at the Call Center will make for an engaging and riveting read and is a must have for all Chetan Bhagat fans.', 'English', 257, 500),
('LIT-18', 'Five Point Someone : What Not To Do At Iit', 'Chetan Bhagat', 176, 116, 35, 10, 'Rupa Publication', '2', 'Literature & Fiction', NULL, 'English', 267, 500),
('LIT-19', 'Revolution 2020: Love Corruption Ambition', 'Chetan Bhagat', 176, 132, 25, 12, 'Rupa Publications', '2', 'Literature & Fiction', 'A tale of dreams, ambitions and unrequited love, Revolution 2020: Love. Ambition. Corruption. explores the lives of three friends from Varanasi, while also painting a stark picture of the country\'s corrupt political landscape', 'English', 296, 500),
('LIT-20', 'The Lost Symbol', 'Dan Brown', 499, 275, 35, 13, 'Transworld', '2', 'Literature & Fiction', 'The Capitol Building, Washington DC: Harvard symbologist Robert Langdon believes he is here to give a lecture. He is wrong. Within minutes of his arrival, a shocking object is discovered. It is a gruesome invitation into an ancient world of hidden wisdom.When Langdon\'s mentor, Peter Solomon - prominent mason and philanthropist - is kidnapped, Langdon realizes that his only hope of saving his friend\'s life is to accept this mysterious summons.It is to take him on a breathless chase through Washington\'s dark history. All that was familiar is changed into a shadowy, mythical world in which Masonic secrets and never-before-seen revelations seem to be leading him to a single impossible and inconceivable truth... # # When Langdon\'s mentor, Peter Solomon - prominent mason and philanthropist - is kidnapped, Langdon realizes that his only hope of saving his friend\'s life is to accept this mysterious summons. # # It is to take him on a breathless chase through Washington\'s dark history. All that was familiar is changed into a shadowy, mythical world in which Masonic secrets and never-before-seen revelations seem to be leading him to a single impossible and inconceivable truth...', 'English', 672, 500),
('LIT-21', 'Lol- An Eclectic Tale Of Love', 'Dan Brown', 300, 240, 20, 9, 'Notion Press', '1', 'Literature & Fiction', 'Description :\r\n\r\nAt times, fortune plays havoc with people’s life expectedly or unexpectedly. Rahul, a painter by birth takes up his father\'s business after completing middle school. In the midst of it, he is forced to leave the house after unveiling the mystery behind his birth. He goes to many places in search of his parents. Finds love with Pragathi, an extremely talented girl, hailing from a middle class family. \r\n\r\nRahul has loved Pragathi for years by now and is waiting for a chance to marry her somehow. With graduations approaching, Rahul has one more decision to make: Pragathi or Parents. It\'s gonna be a hectic reconciliation between the two.But, her dad tries to ignite their love accounting for his status. Will he succeed in roping Pragathi to his side? \r\n\r\nABOUT THE AUTHOR\r\n\r\nRahul Srinivasan was born on 27th of February to his parents S. Vengatesan and S. Geetha in the city of Chennai. Though he\'s from India, he loves to read foreign works and other literature right from childhood. Getting motivated by the writings of Shakespeare and Dan Brown, he decided to write a novel in his own style, and his own way of viewing things which makes him stand unique. He is currently pursuing his college degree in Meenakshi Sundararajan Engineering College, Chennai. \r\n\r\nAs a part of hobby, he writes many short stories and poems in addition to his first novel. He loves to be a role player during short skits and drama. So, in this novel, he takes up the main character named Rahul, and he narrates the entire story in first person which makes the storyline quite impressive, and adds a little bit of suspense.', 'English', 245, 500),
('LIT-22', 'Can Love Happen Twice?', 'Ravinder Singh', 175, 113, 35, 11, 'Penguin Books', '1', 'Literature & Fiction', NULL, 'English', 224, 500),
('LIT-23', 'Tell Me A Story', 'Ravinder Singh', 175, 123, 30, 9, 'Metro Reads', '1', 'Literature & Fiction', 'There is always a story that changed your life\r\nAnd that is the time when life happened for you!\r\nTell Me a Story is collection of heartwarming stories about events and incidents that have affected or changed the lives of the writers in ways that they cannot forget. Happy or sad, inspiring or shocking, these are stories of moments that have left an indelible mark on their lives. Stories, that they would love to share.\r\n\r\nSelected and edited by Ravinder Singh, Tell Me a Story is about moments that make life worth living. It is the second such anthology, after the highly successful Love Stories that Touched My Heart.', 'English', 240, 500),
('LIT-24', 'Your Dreams Are Mine Now', 'Ravinder Singh', 175, 123, 30, 7, 'Penguin Books', '1', 'Literature & Fiction', 'They are complete opposites!\r\nShe\'s a small-town girl who takes admission in Delhi University (DU). An idealist, studies are her first priority. He\'s a Delhi guy, seriously into youth politics in DU. He fights to make his way. Student union elections are his first priority. But then opposites attract as well! A scandal on campus brings them together, they begin to walk the same path and somewhere along, fall in love But their fight against evil comes at a heavy price, which becomes the ultimate test of their lives. Against the backdrop of dominant campus politics, Your Dreams Are Mine Now is an innocent love story that will tug at your heartstrings.', 'English', 272, 381),
('LIT-25', 'Jeffrey Archer - Kane And Abel', 'Jeffrey Archer', 339, 319, 20, 9, 'Pan MacMillan', '1', 'Literature & Fiction', NULL, 'English', 678, 500),
('LIT-26', 'Jeffrey Archer - A Prisoner Of Birth Pb GBP 7.99', 'Jeffrey Archer', 399, 316, 21, 12, 'Panmacmillan', '1', 'Literature & Fiction', NULL, 'English', 560, 500),
('LIT-27', 'Love Curse Of The Rumbaughs', 'Jeffrey Archer', 155, 141, 9, 1, 'Pan Macmillan U.K', '1', 'Literature & Fiction', 'I expect you might think the story I am about to tell you is untrue or perversely gothic in some unhealthy way . . .\' Everyone loves their mother. but what happens when you love her so much you can\'t bear to let her go ever? That\'s the sign of the Love Curse. And Ivy\'s got it . . . bad.', 'English', 248, 200),
('LIT-28', 'Sins Of The Father', 'Jeffrey Archer', 399, 315, 21, 11, 'Macmillan', '1', 'Literature & Fiction', 'The Clifton Chronicles continues with The Sins of the Father, a novel by Jeffrey Archer. Harry Clifton, who calls himself Tom Bradshaw, is arrested and accused of murdering his brother. He is sent to jail and told that he must plead guilty if he is to have a chance at survival. However, his decisions and the decisions of his family may yet test the strength of their bonds and their loyalties. Discover the stories of Hugo Barrington, Emma Barrington, Maisie Clifton, Giles Barrington, and Harry Clifton as the world crumbles under the effects of the Second World War.About Jeffrey ArcherJeffrey Archer is an English writer and former politician. He is known for writing Kane and Abel, Best Kept Secret and Only Time Will Tell.', 'English', 400, 500),
('OTH-1', 'Salman Rushdie\'S Cities', 'Salman Rushdie', 9324, 8476, 9, 11, 'Continuum International Publishing Group', '1', 'others', 'Employing Salman Rushdie as a guide to a historicized contemporary, this study offers an interdisciplinary exploration of the plurality of cities along his transnational trajectory. It engages with the geographically identifiable Bombay, Karachi, Islamabad, London or New York; the phantasmal, politically coded, Jahilia or Mildendo, the inspirational yet flawed urban precedents of Fatehpur Sikri or Renaissance Florence and the ways these cities generate, interact with and transform each other. In contrast with those urban studies which remain in place, this book offers a new understanding of cities wider and constantly shifting interconnections with other cities and places in an unstable, unevenly globalized and dangerously or provocatively local world. The book situates Rushdies cities in relation to developments in Bombay, Karachi, Islamabad and London writing and focuses on novels which shuttle between cities. Parashkevova attends to cities cultural and historical contexts, to many of Rushdies numerous literary, cinematic and artistic influences and to diverse events, processes and paradigms earthquakes, translations, seductions that politically re-position cities and citizens on the contemporary urban map.', 'English', 256, 500),
('LIT-29', 'Salman Rushdie : New Critical Insights ( Vol. 1 )', 'Salman Rushdie', 750, 653, 13, 14, 'Atlantic', '1', 'Literature & Fiction', 'Rushdie has put behind him the political and religious controversy that surrounded him in the aftermath of the appearance of The Satanic Verses. These two volumes endeavour to continue the literary-critical study of his works by bringing together some of the best critical essays written in the post-?Verses controversy? period. The essays present an honest assessment of Rushdie?s works by creatively engaging with the issues each of them raises.About Author:Rajeshwar Mittapalli is Associate Professor of English at Kakatiya University, Warangal, Andhra Pradesh, India. His published works of criticism include The Novels of Wole Soyinka and Indian Women Novelists and Psychoanalysis. So far he has edited 20 anthologies of literary essays. They include Post-modernism and English Literature, Indian Fiction in English, Studies in Indian Writing in English, Volume 1 & 2, Post-Independence Indian English Fiction, Commonwealth Fiction: Twenty-first Century Readings, Modern American Literature, V.S. Naipaul: Fiction and Travel Writing, Modern Criticism and IT Revolution, Globalization and the Teaching of English.Dr. Mittapalli is currently the editor of The Atlantic Literary Review published from New Delhi. He is also the ex-officio editor of Kakatiya Journal of English Studies, an official publication of the Department of English, Kakatiya University, Warangal.He has published 32 articles on Indian, African and American fiction and ELT in such reputed journals as New Quest, ARTSresearch, Indian Literature, The Journal of Indian Writing in English, Commonwealth Quarterly, The Commonwealth Review and Revaluations.Joel Kuortti is Acting Professor of English at the University of Tampere, Finland. He has published three works on Rushdie: The Salman Rushdie Bibliography (1997), Place of the Sacred (1997), and Fictions to Live In (1998). Currently he is working on Indian English literature and has compiled an extensive bibliography of Indian women?s writing in English.', 'English', 248, 500),
('LIT-30', 'Torn', 'J K Rowling', 399, 296, 26, 31, 'Pan Macmillan', '1', 'Literature & Fiction', 'Acknowledging that she was different from everyone else wasn\'t difficult for Wendy Everly she\'d always felt like an outsider. But a new world and new family is a hard for any girl to accept easily. Leaving behind the mysterious country of her birth, she is determined to fit back into normal life. But the world she\'s left behind won\'t let her go that easily. Kidnapped and imprisoned by her true family\'s enemies, Wendy soon learns that the lines between good and evil aren\'t as defined as she thought. And those things she\'d taken for granted may have been lies all along. With the help of the dangerously attractive Loki, she escapes back to the safety of F rening only to be confronted by a new threat. It\'s time to make a choice can she put aside her personal feelings for the sake of her country? Torn between duty and love she must make a choice that could destroy her one chance at true happiness.Generated an excitement not felt in the industry since Stephenie Meyer or perhaps even J. K. Rowling\' New York Times,A fast paced romance addictive\' Guardian on Switched , \'Drew me in and kept me hooked...cracking pace\' Sunday Express on Switched', 'English', 356, 500),
('LIT-31', 'Harry Potter and the Half-Blood Prince', 'J K Rowling', 699, 454, 35, 32, 'Bloomsbury', '1', 'Literature & Fiction', NULL, 'English', 420, 500),
('LIT-32', 'Career Of Evil : A Cormoran Strike Novel', 'J K Rowling', 699, 365, 35, 23, 'Little, Brown Book Group', '1', 'Literature & Fiction', 'The third book in the highly acclaimed crime fiction series by J. K. Rowling, writing under the pseudonym Robert Galbraith. When a mysterious package is delivered to Robin Ellacott, she is horrified to discover that it contains a woman\'s severed leg. Her boss, private detective Cormoran Strike, is less surprised but no less alarmed. There are four people from his past who he thinks could be responsible - and Strike knows that any one of them is capable of sustained and unspeakable brutality. With the police focusing on the one suspect Strike is increasingly sure is not the perpetrator, he and Robin take matters into their own hands and delve into the dark and twisted worlds of the other three men. But as more horrendous acts occur, time is running out for the two of them... A fiendishly clever mystery with unexpected twists around every corner, Career of Evil is also a gripping story of a man and a woman at a crossroads in their personal and professional lives. You will not be able to put this book down.\r\n\r\nAbout the Author\r\n\r\nRobert Galbraith is a pseudonym for J. K. Rowling, bestselling author of the Harry Potter series and The Casual Vacancy. Career of Evil is the third book in the highly acclaimed Cormoran Strike crime fiction series. The Cuckoos Calling was published in 2013 and The Silkworm in 2014. Robert Galbraiths Cormoran Strike novels will be adapted for a major new television series for BBC One, produced by Bront Film and Television. Robert Galbraith / J. K. Rowling will not be available for interview or events.', 'English', 512, 500),
('LIT-33', 'Harry Potter And The Goblet Of Fire', 'J k Rowling', 699, 510, 27, 13, 'Bloomsbury', '1', 'Literature & Fiction', NULL, 'English', 427, 500);

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `users`
--

CREATE TABLE `users` (
  `UserName` varchar(40) COLLATE utf8_unicode_ci NOT NULL,
  `Password` varchar(40) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `users`
--

INSERT INTO `users` (`UserName`, `Password`) VALUES
('test', '123'),
('leduc0605', '123456789');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `cart`
--
ALTER TABLE `cart`
  ADD PRIMARY KEY (`Customer`,`Product`),
  ADD KEY `Product` (`Product`);

--
-- Chỉ mục cho bảng `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`PID`);

--
-- Chỉ mục cho bảng `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`UserName`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
